Various improvements.
  - Support Linux.
  - Sync Darwin configuration with trunk.
  - Add /etc/paths.d/10-pkgsrc on Darwin.
  - Work around joyent/pkgsrc#303.
  - Make 'set -e' clean, and ensure we report failure correctly.
  - Use some variables to keep it under 80 columns.

diff --git a/scripts/mk-release-bootstrap b/scripts/mk-release-bootstrap
--- a/scripts/mk-release-bootstrap
+++ b/scripts/mk-release-bootstrap
@@ -13,14 +13,24 @@ fi
 # Load per-pkgbuild config
 . $(dirname $0)/../conf/${pkgbuild}/pkgbuild.conf
 
+# Helpful aliases
+RELEASE_TAR="${LOCAL_PACKAGE_BASEDIR}/${BOOTSTRAP_RELEASE_DIR}/${BOOTSTRAP_KIT}.tar.gz"
+RELEASE_ASC="${RELEASE_TAR}.asc"
+
 ${CHROOT_CREATE} ${CHROOT_BASEDIR}/bootstrap-${pkgbuild}
 /usr/sbin/chroot ${CHROOT_BASEDIR}/bootstrap-${pkgbuild} /bin/bash -c "
+	set -e
 	PATH=${PBULK_PATH}
 	${TAR} -zxf ${LOCAL_PACKAGE_BASEDIR}/${BOOTSTRAP_PBULK_DIR}/${BOOTSTRAP_KIT}.tar.gz -C /
 	PATH=${PREFIX}/sbin:${PREFIX}/bin:${PBULK_PATH}
 	PKG_PATH=${LOCAL_PACKAGE_BASEDIR}/${LOCAL_PACKAGE_DIR}/${binpkgpath}/All ${PREFIX}/sbin/pkg_add \
 	    mozilla-rootcerts pkg_alternatives pkgin pkgsrc-gnupg-keys
-	${PREFIX}/sbin/mozilla-rootcerts install >/dev/null
+	# Avoid 'install' as it fails if /etc/ssl/certs exists.
+	(
+		cd ${SYSCONFDIR}/openssl/certs
+		${PREFIX}/sbin/mozilla-rootcerts extract >/dev/null
+		${PREFIX}/sbin/mozilla-rootcerts rehash >/dev/null
+	)
 	rm -f ${PREFIX}/.dlj_license_accepted
 	ed ${SYSCONFDIR}/mk.conf >/dev/null 2>&1 <<-EOF
 		1,5d
@@ -62,15 +72,14 @@ ${CHROOT_CREATE} ${CHROOT_BASEDIR}/bootstrap-${pkgbuild}
 			w
 			q
 		EOF
-	# XXX: Assume OSX for now, tidy later.
-	else
+	elif [ '${OPSYS}' = 'Darwin' ]; then
 		ed ${SYSCONFDIR}/mk.conf >/dev/null 2>&1 <<-EOF
 			a
 
 			FETCH_USING=		curl
 			MULTILIB_SUPPORTED=	no
-			X11_TYPE=		native
-			X11BASE=		/opt/X11
+			PKGSRC_FORTRAN=		gfortran
+			X11_TYPE=		modular
 
 			.
 			r ${PKGBUILD_BASEDIR}/include/pkgoptions/osx.mk
@@ -102,19 +111,36 @@ ${CHROOT_CREATE} ${CHROOT_BASEDIR}/bootstrap-${pkgbuild}
 			q
 		EOF
 	fi
+	tarextras=
+	slashprivate=
+	if [ '${OPSYS}' = 'Darwin' ]; then
+		echo '${PREFIX}/sbin' >/etc/paths.d/10-pkgsrc
+		echo '${PREFIX}/bin' >>/etc/paths.d/10-pkgsrc
+		tarextras='./private/etc/paths.d/10-pkgsrc'
+		# Work around El Capitan 'Cannot extract through symlink var'.
+		if [ '${VARBASE}' = '/var' ]; then
+			slashprivate='/private'
+		fi
+	fi
+	mkdir -p \${slashprivate}${VARBASE}/db/pkgin/cache
 	mkdir -p ${LOCAL_PACKAGE_BASEDIR}/${BOOTSTRAP_RELEASE_DIR}
-	mkdir -p ${VARBASE}/db/pkgin/cache
-	${TAR} -zc -C / --exclude '.fseventsd' --exclude '.metadata_never_index' \
-	    -f ${LOCAL_PACKAGE_BASEDIR}/${BOOTSTRAP_RELEASE_DIR}/${BOOTSTRAP_KIT}.tar.gz \
-	    .${PREFIX} .${VARBASE}/db/pkgin/cache
+	${TAR} -zc -f ${RELEASE_TAR} -C / \
+	    --exclude '.fseventsd' --exclude '.metadata_never_index' \
+	    .${PREFIX} .\${slashprivate}${VARBASE}/db/pkgin/cache \${tarextras}
 	if [ -n '${GPG_SIGN_AS}' ]; then
-		rm -f ${LOCAL_PACKAGE_BASEDIR}/${BOOTSTRAP_RELEASE_DIR}/${BOOTSTRAP_KIT}.tar.gz.asc
-		${GPG} --armor --sign --detach \
-		    ${LOCAL_PACKAGE_BASEDIR}/${BOOTSTRAP_RELEASE_DIR}/${BOOTSTRAP_KIT}.tar.gz
+		rm -f ${RELEASE_ASC}
+		${GPG} --armor --sign --detach -u ${GPG_SIGN_AS} ${RELEASE_TAR}
 	fi
 "
+bsret=$?
 ${CHROOT_DELETE} ${CHROOT_BASEDIR}/bootstrap-${pkgbuild}
-echo "Created ${LOCAL_PACKAGE_BASEDIR}/${BOOTSTRAP_RELEASE_DIR}/${BOOTSTRAP_KIT}.tar.gz"
-if [ -n "${GPG_SIGN_AS}" ]; then
-	echo "Created ${LOCAL_PACKAGE_BASEDIR}/${BOOTSTRAP_RELEASE_DIR}/${BOOTSTRAP_KIT}.tar.gz.asc"
+chret=$?
+if [ ${bsret} -eq 0 ]; then
+	echo "Created ${RELEASE_TAR}"
+	if [ -n "${GPG_SIGN_AS}" ]; then
+		echo "Created ${RELEASE_ASC}"
+	fi
+else
+	echo "Bootstrap creation failed."
 fi
+exit $((${bsret} + ${chret}))
