Ensure OS checks are at the beginning of scripts.

diff --git a/scripts/mksandbox b/scripts/mksandbox
--- a/scripts/mksandbox
+++ b/scripts/mksandbox
@@ -3,6 +3,11 @@
 # Create a per-pkgbuild chroot area.
 #
 
+if [ "$(uname -s)" != "SunOS" ]; then
+	echo "ERROR: Script is only suitable for SunOS." >&2
+	exit 1
+fi
+
 set -e
 
 PATH=/sbin:/usr/sbin:/usr/bin
@@ -13,11 +18,6 @@ if [ $# -eq 1 ]; then
 else
 	echo "usage: $0 <chrootdir>" >&2
 	exit 2
-fi
-
-if [ "$(uname -s)" != "SunOS" ]; then
-	echo "ERROR: Script is only suitable for SunOS." >&2
-	exit 1
 fi
 
 if [ -d "${chrootdir}" ]; then
diff --git a/scripts/mksandbox-osx b/scripts/mksandbox-osx
--- a/scripts/mksandbox-osx
+++ b/scripts/mksandbox-osx
@@ -3,17 +3,17 @@
 # Create a shadowed sandbox from the root file system ready for builds.
 #
 
+if [ "$(uname -s)" != "Darwin" ]; then
+	echo "ERROR: Script is only suitable for OSX." >&2
+	exit 1
+fi
+
 if [ $# -eq 1 ]; then
 	chrootdir=$1; shift
 	chrootname=$(basename ${chrootdir})
 else
 	echo "usage: $0 <chrootdir>" >&2
 	exit 2
-fi
-
-if [ "$(uname -s)" != "Darwin" ]; then
-        echo "ERROR: Script is only suitable for OSX." >&2
-        exit 1
 fi
 
 while true; do
diff --git a/scripts/rmsandbox b/scripts/rmsandbox
--- a/scripts/rmsandbox
+++ b/scripts/rmsandbox
@@ -3,6 +3,11 @@
 # Delete a per-pkgbuild chroot area.
 #
 
+if [ "$(uname -s)" != "SunOS" ]; then
+	echo "ERROR: Script is only suitable for SunOS." >&2
+	exit 1
+fi
+
 PATH=/sbin:/usr/sbin:/usr/bin
 
 if [ $# -eq 1 ]; then
diff --git a/scripts/rmsandbox-osx b/scripts/rmsandbox-osx
--- a/scripts/rmsandbox-osx
+++ b/scripts/rmsandbox-osx
@@ -3,9 +3,14 @@
 # Unmount a shadowed sandbox
 #
 
+if [ "$(uname -s)" != "Darwin" ]; then
+	echo "ERROR: Script is only suitable for OSX." >&2
+	exit 1
+fi
+
 if [ $# -eq 1 ]; then
 	chrootdir="${1%%/}"; shift
-        chrootname=$(basename ${chrootdir})
+	chrootname=$(basename ${chrootdir})
 else
 	echo "usage: $0 <chrootdir>" >&2
 	exit 2
@@ -14,11 +19,6 @@ fi
 if [ ! -d ${chrootdir} ]; then
 	echo "ERROR: ${chrootdir} does not exist." >&2
 	exit 1
-fi
-
-if [ "$(uname -s)" != "Darwin" ]; then
-        echo "ERROR: Script is only suitable for OSX." >&2
-        exit 1
 fi
 
 # Calculate pkgbuild based on chroot name.
