Ensure running sandbox scripts on the correct OS.

diff --git a/scripts/mksandbox-linux b/scripts/mksandbox-linux
--- a/scripts/mksandbox-linux
+++ b/scripts/mksandbox-linux
@@ -11,6 +11,11 @@ else
 	exit 2
 fi
 
+if [ "$(uname -s)" != "Linux" ]; then
+        echo "ERROR: Script is only suitable for Linux." >&2
+        exit 1
+fi
+
 while true; do
 	if [ -d ${chrootdir} ]; then
 		sleep 5
diff --git a/scripts/mksandbox-osx b/scripts/mksandbox-osx
--- a/scripts/mksandbox-osx
+++ b/scripts/mksandbox-osx
@@ -11,6 +11,11 @@ else
 	exit 2
 fi
 
+if [ "$(uname -s)" != "Darwin" ]; then
+        echo "ERROR: Script is only suitable for OSX." >&2
+        exit 1
+fi
+
 while true; do
 	if [ -d ${chrootdir} ]; then
 		#echo "${chrootdir} already exists, retrying or ^C" >&2
diff --git a/scripts/rmsandbox-linux b/scripts/rmsandbox-linux
--- a/scripts/rmsandbox-linux
+++ b/scripts/rmsandbox-linux
@@ -1,6 +1,16 @@
 #!/bin/bash
 
-chrootdir=`echo $1 | sed -e 's,/$,,'`; shift
+if [ $# -eq 1 ]; then
+	chrootdir="${1%%/}"; shift
+else
+	echo "usage: $0 <chrootdir>" >&2
+	exit 2
+fi
+
+if [ "$(uname -s)" != "Linux" ]; then
+	echo "ERROR: Script is only suitable for Linux." >&2
+	exit 1
+fi
 
 if [ -d ${chrootdir} ]; then
 	#
diff --git a/scripts/rmsandbox-osx b/scripts/rmsandbox-osx
--- a/scripts/rmsandbox-osx
+++ b/scripts/rmsandbox-osx
@@ -16,6 +16,11 @@ if [ ! -d ${chrootdir} ]; then
 	exit 1
 fi
 
+if [ "$(uname -s)" != "Darwin" ]; then
+        echo "ERROR: Script is only suitable for OSX." >&2
+        exit 1
+fi
+
 # Calculate pkgbuild based on chroot name.
 pkgbuild=${chrootname}
 pkgbuild=${pkgbuild#bootstrap-pbulk-}
