mksandbox: Ensure script only runs on SunOS.

diff --git a/scripts/mksandbox b/scripts/mksandbox
--- a/scripts/mksandbox
+++ b/scripts/mksandbox
@@ -15,6 +15,11 @@ else
 	exit 2
 fi
 
+if [ "$(uname -s)" != "SunOS" ]; then
+	echo "ERROR: Script is only suitable for SunOS." >&2
+	exit 1
+fi
+
 if [ -d "${chrootdir}" ]; then
 	echo "Chroot directory ${chrootdir} already exists.  Not recreating"
 	exit 0
@@ -224,5 +229,6 @@ if [ -n "${TOOLS_BOOTSTRAP}" ]; then
 				q
 			EOF
 		fi
-		${TOOLS_BASEDIR}/sbin/pkg_add ${TOOLS_COMPILER} ${tools_packages} >/dev/null 2>&1"
+		${TOOLS_BASEDIR}/sbin/pkg_add ${TOOLS_COMPILER} ${tools_packages} >/dev/null 2>&1
+	"
 fi
